Revert "update MediePortal"
This reverts commit 645ed8d2aa638ecf8ef317584c29ef09deffb8c3.

build broken
    assert signature == "!<arch>\n" or signature == b"!<arch>\n", "Old ipk format (non-deb) is unsupported, file: %s, magic: %s, expected %s" % (fn, signature, "!<arch>")
AssertionError: Old ipk format (non-deb) is unsupported, file: /home/oe1/atv64/build-enviroment/builds/openatv/release/hd530c/tmp/deploy/ipk/3rdparty/enigma2-plugin-extensions-mediaportal_all.ipk, magic: b'<html><head>\n', expected !<arch>